export const API_TAGS = {
    PROFILE: "profile",
    APPS: "apps",
    URLS: "urls",
    appUrlDASHBOARD: "appUrlDashboard",
    EVENTS: "events",
    ATTENDANCE: "attendance",
    SCHEDULES: "schedules",
    CLIENTS: "clients",
    COMPANY: "company",
    dashboardSTATS: "dashboardStats",
    coreMEMBER: "coreMember",
    memberSTATS: "memberStats",
    todayWorkTIME: "todayWorkTime",
    insightsDASHBOARD: "insightsDashboard",
    googleINTEGRATION: "google-integration",
    googleEVENTS: "google-events",
    microsoftINTEGRATION: "microsoft-integration",
    microsoftEVENTS: "microsoft-events",
    LEAVES: "leaves",
    leaveHOLIDAYS: "leave-holidays",
    leaveTYPES: "leave-types",
    MEMBERS: "members",
    NOTIFICATIONS: "notifications",
    PROJECTS: "projects",
    timeENTRY: "timeEntry",
    SCREENSHOTS: "screenshots",
    monthlyREPORT: "monthly-report",
    TASKS: "tasks",
    manualTimeENTRY: "manualTimeEntry",

} as const;