import { toast } from "sonner";
import type jsPDF from "jspdf";

import { getPayrollRun } from "@/actions/payroll/action";
import {
  formatPayrollHours,
  formatPayrollMoney,
  formatPayrollPeriod,
} from "@/lib/payroll";
import {
  EmployeePayroll,
  PayrollRun,
  RUN_STATUS_LABELS,
  SALARY_TYPE_LABELS,
} from "@/types/payroll";
import {
  PAGE_MARGIN,
  PDF_PALETTE,
  STATUS_COLOR,
  TABLE_STYLES,
  dateRange,
  drawBadge,
  drawCard,
  drawDivider,
  drawFooter,
  drawNotesBlock,
  drawText,
  drawTopBrandBar,
  lastTableBottom,
  loadPdfLibs,
  safeDate,
  slugify,
  type Rgb,
} from "./payrollPdfKit";

/**
 * Single source of truth for the payslip table: header, cell and column style
 * travel together so inserting a column can't leave the styles pointing at the
 * wrong index.
 */
const PDF_COLUMNS: Array<{
  header: string;
  cell: (item: EmployeePayroll, runCurrency: string) => string;
  style?: Record<string, unknown>;
}> = [
  {
    header: "Employee",
    cell: (it) => `${it.user?.name ?? "—"}\n${it.user?.email ?? ""}`,
    style: { cellWidth: 130 },
  },
  {
    header: "Type",
    cell: (it) => SALARY_TYPE_LABELS[it.salary_type] ?? it.salary_type,
    style: { cellWidth: 60 },
  },
  { header: "Target", cell: (it) => formatPayrollHours(it.target_hours) },
  { header: "Worked", cell: (it) => formatPayrollHours(it.worked_hours) },
  { header: "Leave", cell: (it) => formatPayrollHours(it.leave_hours) },
  { header: "Holiday", cell: (it) => formatPayrollHours(it.holiday_hours) },
  { header: "Overtime", cell: (it) => formatPayrollHours(it.overtime_hours) },
  { header: "Payable", cell: (it) => formatPayrollHours(it.payable_hours) },
  {
    header: "Basic",
    cell: (it, currency) => formatPayrollMoney(it.basic_salary, currency),
    style: { halign: "right" },
  },
  {
    header: "OT amount",
    cell: (it, currency) => formatPayrollMoney(it.overtime_amount, currency),
    style: { halign: "right" },
  },
  {
    header: "Deduction",
    cell: (it, currency) => formatPayrollMoney(it.deduction_amount, currency),
    style: { halign: "right" },
  },
  {
    // Waived and Bonus are in the employee's own currency, not the run's.
    header: "Waived",
    cell: (it) =>
      it.deduction_waived
        ? formatPayrollMoney(it.waived_amount, it.currency)
        : "—",
    style: { halign: "right" },
  },
  {
    header: "Bonus",
    cell: (it) =>
      Number(it.adjustment_total || 0) > 0
        ? formatPayrollMoney(it.adjustment_total, it.currency)
        : "—",
    style: { halign: "right" },
  },
  {
    header: "Final",
    cell: (it, currency) => formatPayrollMoney(it.final_salary, currency),
    style: { fontStyle: "bold", halign: "right" },
  },
];

const drawHeader = (doc: jsPDF, run: PayrollRun) => {
  drawTopBrandBar(doc);

  drawText(doc, "Payroll Run Report", PAGE_MARGIN, 34, {
    size: 16,
    bold: true,
    color: PDF_PALETTE.heading,
  });
  drawText(
    doc,
    `${formatPayrollPeriod(run.month, run.year)}  ·  Run #${run.id}  ·  ${run.currency}`,
    PAGE_MARGIN,
    50,
    { size: 10 },
  );

  drawBadge(
    doc,
    RUN_STATUS_LABELS[run.status] ?? run.status,
    doc.internal.pageSize.getWidth() - PAGE_MARGIN,
    22,
    STATUS_COLOR[run.status] ?? PDF_PALETTE.subtext,
  );

  drawDivider(doc, 62);
};

const drawMetaBlock = (doc: jsPDF, run: PayrollRun) => {
  const rows: Array<[string, string]> = [
    ["Period", dateRange(run.period_start, run.period_end)],
    ["Generated by", run.generatedBy?.name ? `${run.generatedBy.name}` : "—"],
    [
      "Approved",
      run.approved_at
        ? `${safeDate(run.approved_at)}${
            run.approvedBy?.name ? ` · ${run.approvedBy.name}` : ""
          }`
        : "Not yet approved",
    ],
  ];

  rows.forEach(([label, value], idx) => {
    const y = 78 + idx * 14;
    drawText(doc, label.toUpperCase(), PAGE_MARGIN, y, { size: 9 });
    drawText(doc, value, PAGE_MARGIN + 90, y, {
      size: 9,
      bold: true,
      color: PDF_PALETTE.heading,
    });
  });
};

const drawStatCards = (doc: jsPDF, run: PayrollRun) => {
  const y = 132;
  const gap = 12;
  const totalWidth = doc.internal.pageSize.getWidth() - PAGE_MARGIN * 2;
  const cardW = (totalWidth - gap * 3) / 4;
  const cardH = 58;

  const cards: Array<{
    label: string;
    value: string;
    hint: string;
    accent: Rgb;
  }> = [
    {
      label: "Total Employees",
      value: String(run.total_employees),
      hint: `${run.generated_count} generated · ${run.failed_count} failed`,
      accent: PDF_PALETTE.brand,
    },
    {
      label: "Total Gross",
      value: formatPayrollMoney(run.total_gross, run.currency),
      hint: "Before deductions & overtime",
      accent: [139, 92, 246],
    },
    {
      label: "Total Net",
      value: formatPayrollMoney(run.total_net, run.currency),
      hint: "Amount payable to employees",
      accent: [59, 130, 246],
    },
    {
      label: "Currency",
      value: run.currency,
      hint: "Applies to all items in this run",
      accent: [234, 179, 8],
    },
  ];

  cards.forEach((card, i) => {
    const x = PAGE_MARGIN + i * (cardW + gap);
    drawCard(doc, x, y, cardW, cardH, { accent: card.accent });
    drawText(doc, card.label.toUpperCase(), x + 12, y + 15, { size: 8, bold: true });
    drawText(doc, card.value, x + 12, y + 34, {
      size: 14,
      bold: true,
      color: PDF_PALETTE.heading,
    });
    drawText(doc, card.hint, x + 12, y + 48, { size: 8 });
  });
};

export const downloadPayrollPdf = async (runId: number) => {
  try {
    const PAGE_SIZE = 500;
    const first = await getPayrollRun(runId, { page: 1, limit: PAGE_SIZE });
    if (!first?.success || !first?.data) {
      toast.error(first?.message ?? "Unable to prepare PDF.");
      return;
    }

    const { run } = first.data as { run: PayrollRun };
    const items: EmployeePayroll[] = [
      ...((first.data as { items: EmployeePayroll[] }).items ?? []),
    ];

    const total = first.meta?.total ?? items.length;
    const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

    const pdfLibsPromise = loadPdfLibs();

    for (let page = 2; page <= totalPages; page += 1) {
      const next = await getPayrollRun(runId, { page, limit: PAGE_SIZE });
      if (next?.success && next?.data) {
        items.push(...((next.data as { items: EmployeePayroll[] }).items ?? []));
      }
    }

    const { JsPDF, autoTable } = await pdfLibsPromise;
    const doc = new JsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

    drawHeader(doc, run);
    drawMetaBlock(doc, run);
    drawStatCards(doc, run);

    const tableStartY = 210;
    const currency = run.currency;

    autoTable(doc, {
      startY: tableStartY,
      head: [PDF_COLUMNS.map((column) => column.header)],
      body: items.map((it) =>
        PDF_COLUMNS.map((column) => column.cell(it, currency)),
      ),
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      ...TABLE_STYLES,
      columnStyles: Object.fromEntries(
        PDF_COLUMNS.flatMap((column, index) =>
          column.style ? [[index, column.style]] : [],
        ),
      ),
    });

    const afterTableY = lastTableBottom(doc, tableStartY) + 20;

    if (run.notes) {
      drawNotesBlock(doc, run.notes, afterTableY);
    }

    drawFooter(doc);

    doc.save(
      `payroll-${slugify(formatPayrollPeriod(run.month, run.year))}-run-${run.id}.pdf`,
    );
    toast.success("PDF downloaded.");
  } catch (error) {
    toast.error(
      error instanceof Error ? error.message : "Failed to build PDF.",
    );
  }
};
