import { toast } from "sonner";
import { format, parseISO } from "date-fns";
import type jsPDF from "jspdf";

import { getPayrollRun } from "@/actions/payroll/action";
import {
  formatPayrollHours,
  formatPayrollMoney,
  formatPayrollPeriod,
} from "@/lib/payroll";
import {
  EmployeePayroll,
  PayrollRun,
  RUN_STATUS_LABELS,
  SALARY_TYPE_LABELS,
} from "@/types/payroll";

const BRAND_GREEN: [number, number, number] = [18, 205, 105];
const HEADING: [number, number, number] = [15, 22, 19];
const SUBTEXT: [number, number, number] = [80, 85, 83];
const BORDER: [number, number, number] = [220, 227, 227];
const SOFT_BG: [number, number, number] = [246, 247, 249];

const STATUS_COLOR: Record<string, [number, number, number]> = {
  draft: [100, 116, 139],
  generated: [59, 130, 246],
  approved: [16, 185, 129],
  paid: [139, 92, 246],
};

const safeDate = (value?: string | null) => {
  if (!value) return "—";
  try {
    return format(parseISO(value), "MMM d, yyyy h:mm a");
  } catch {
    return value;
  }
};

const shortDate = (value?: string | null) => {
  if (!value) return "—";
  try {
    return format(parseISO(value), "MMM d, yyyy");
  } catch {
    return value;
  }
};

const drawHeader = (doc: jsPDF, run: PayrollRun) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;

  doc.setFillColor(...BRAND_GREEN);
  doc.rect(0, 0, pageWidth, 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...HEADING);
  doc.text("Payroll Run Report", marginX, 34);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...SUBTEXT);
  doc.text(
    `${formatPayrollPeriod(run.month, run.year)}  ·  Run #${run.id}  ·  ${run.currency}`,
    marginX,
    50,
  );

  const status = STATUS_COLOR[run.status] ?? SUBTEXT;
  const label = RUN_STATUS_LABELS[run.status] ?? run.status;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  const badgeText = label.toUpperCase();
  const textWidth = doc.getTextWidth(badgeText);
  const padX = 10;
  const badgeW = textWidth + padX * 2;
  const badgeH = 18;
  const badgeX = pageWidth - marginX - badgeW;
  const badgeY = 22;
  doc.setFillColor(status[0], status[1], status[2]);
  doc.roundedRect(badgeX, badgeY, badgeW, badgeH, 4, 4, "F");
  doc.setTextColor(255, 255, 255);
  doc.text(badgeText, badgeX + padX, badgeY + 12);

  doc.setDrawColor(...BORDER);
  doc.setLineWidth(0.6);
  doc.line(marginX, 62, pageWidth - marginX, 62);
};

const drawMetaBlock = (doc: jsPDF, run: PayrollRun) => {
  const marginX = 40;
  const y = 78;

  const rows: Array<[string, string]> = [
    [
      "Period",
      `${shortDate(run.period_start)} → ${shortDate(run.period_end)}`,
    ],
    [
      "Generated by",
      run.generatedBy?.name ? `${run.generatedBy.name}` : "—",
    ],
    [
      "Approved",
      run.approved_at
        ? `${safeDate(run.approved_at)}${
            run.approvedBy?.name ? ` · ${run.approvedBy.name}` : ""
          }`
        : "Not yet approved",
    ],
  ];

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  rows.forEach(([label, value], idx) => {
    const rowY = y + idx * 14;
    doc.setTextColor(...SUBTEXT);
    doc.text(label.toUpperCase(), marginX, rowY);
    doc.setTextColor(...HEADING);
    doc.setFont("helvetica", "bold");
    doc.text(value, marginX + 90, rowY);
    doc.setFont("helvetica", "normal");
  });
};

const drawStatCards = (doc: jsPDF, run: PayrollRun) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;
  const y = 132;
  const gap = 12;
  const totalWidth = pageWidth - marginX * 2;
  const cardW = (totalWidth - gap * 3) / 4;
  const cardH = 58;

  const cards: Array<{
    label: string;
    value: string;
    hint: string;
    accent: [number, number, number];
  }> = [
    {
      label: "Total Employees",
      value: String(run.total_employees),
      hint: `${run.generated_count} generated · ${run.failed_count} failed`,
      accent: BRAND_GREEN,
    },
    {
      label: "Total Gross",
      value: formatPayrollMoney(run.total_gross, run.currency),
      hint: "Before deductions & overtime",
      accent: [139, 92, 246],
    },
    {
      label: "Total Net",
      value: formatPayrollMoney(run.total_net, run.currency),
      hint: "Amount payable to employees",
      accent: [59, 130, 246],
    },
    {
      label: "Currency",
      value: run.currency,
      hint: "Applies to all items in this run",
      accent: [234, 179, 8],
    },
  ];

  cards.forEach((c, i) => {
    const x = marginX + i * (cardW + gap);
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(...BORDER);
    doc.setLineWidth(0.8);
    doc.roundedRect(x, y, cardW, cardH, 6, 6, "FD");

    doc.setFillColor(c.accent[0], c.accent[1], c.accent[2]);
    doc.roundedRect(x, y, 3, cardH, 1.5, 1.5, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...SUBTEXT);
    doc.text(c.label.toUpperCase(), x + 12, y + 15);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...HEADING);
    doc.text(c.value, x + 12, y + 34);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...SUBTEXT);
    doc.text(c.hint, x + 12, y + 48);
  });
};

const drawNotes = (doc: jsPDF, notes: string, startY: number) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 40;
  const boxWidth = pageWidth - marginX * 2;

  const wrapped = doc.splitTextToSize(notes, boxWidth - 20) as string[];
  const boxHeight = 18 + wrapped.length * 12;

  doc.setFillColor(...SOFT_BG);
  doc.setDrawColor(...BORDER);
  doc.roundedRect(marginX, startY, boxWidth, boxHeight, 6, 6, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...HEADING);
  doc.text("NOTES", marginX + 10, startY + 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...SUBTEXT);
  doc.text(wrapped, marginX + 10, startY + 28);

  return startY + boxHeight;
};

const drawFooter = (doc: jsPDF) => {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generated = format(new Date(), "MMM d, yyyy h:mm a");

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...SUBTEXT);
    doc.text(`Generated ${generated}`, 40, pageHeight - 18);
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 40,
      pageHeight - 18,
      { align: "right" },
    );
  }
};

export const downloadPayrollPdf = async (runId: number) => {
  try {
    const PAGE_SIZE = 500;
    const first = await getPayrollRun(runId, { page: 1, limit: PAGE_SIZE });
    if (!first?.success || !first?.data) {
      toast.error(first?.message ?? "Unable to prepare PDF.");
      return;
    }

    const { run } = first.data as { run: PayrollRun };
    const items: EmployeePayroll[] = [
      ...((first.data as { items: EmployeePayroll[] }).items ?? []),
    ];

    const total = first.meta?.total ?? items.length;
    const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));

    const pdfLibsPromise = Promise.all([
      import("jspdf"),
      import("jspdf-autotable"),
    ]);

    for (let page = 2; page <= totalPages; page += 1) {
      const next = await getPayrollRun(runId, { page, limit: PAGE_SIZE });
      if (next?.success && next?.data) {
        items.push(...((next.data as { items: EmployeePayroll[] }).items ?? []));
      }
    }

    const [{ default: JsPDF }, { default: autoTable }] = await pdfLibsPromise;
    const doc = new JsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

    drawHeader(doc, run);
    drawMetaBlock(doc, run);
    drawStatCards(doc, run);

    const tableStartY = 210;
    const currency = run.currency;

    autoTable(doc, {
      startY: tableStartY,
      head: [[
        "Employee",
        "Type",
        "Target",
        "Worked",
        "Leave",
        "Holiday",
        "Overtime",
        "Payable",
        "Basic",
        "OT amount",
        "Deduction",
        "Final",
      ]],
      body: items.map((it) => [
        `${it.user?.name ?? "—"}\n${it.user?.email ?? ""}`,
        SALARY_TYPE_LABELS[it.salary_type] ?? it.salary_type,
        formatPayrollHours(it.target_hours),
        formatPayrollHours(it.worked_hours),
        formatPayrollHours(it.leave_hours),
        formatPayrollHours(it.holiday_hours),
        formatPayrollHours(it.overtime_hours),
        formatPayrollHours(it.payable_hours),
        formatPayrollMoney(it.basic_salary, currency),
        formatPayrollMoney(it.overtime_amount, currency),
        formatPayrollMoney(it.deduction_amount, currency),
        formatPayrollMoney(it.final_salary, currency),
      ]),
      margin: { left: 40, right: 40 },
      styles: {
        font: "helvetica",
        fontSize: 8.5,
        cellPadding: 6,
        textColor: HEADING,
        lineColor: BORDER,
        lineWidth: 0.4,
        valign: "middle",
      },
      headStyles: {
        fillColor: HEADING,
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8.5,
        cellPadding: 7,
      },
      bodyStyles: { fillColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: SOFT_BG },
      columnStyles: {
        0: { cellWidth: 130 },
        1: { cellWidth: 60 },
        11: { fontStyle: "bold", halign: "right" },
        8: { halign: "right" },
        9: { halign: "right" },
        10: { halign: "right" },
      },
      didDrawPage: () => {
        // header only drawn once on page 1; keep pages clean
      },
    });

    interface AutoTableDoc extends jsPDF {
      lastAutoTable?: { finalY: number };
    }
    const afterTableY = ((doc as AutoTableDoc).lastAutoTable?.finalY ?? tableStartY) + 20;

    if (run.notes) {
      drawNotes(doc, run.notes, afterTableY);
    }

    drawFooter(doc);

    const filename = `payroll-${formatPayrollPeriod(run.month, run.year)
      .toLowerCase()
      .replace(/\s+/g, "-")}-run-${run.id}.pdf`;

    doc.save(filename);
    toast.success("PDF downloaded.");
  } catch (error) {
    toast.error(
      error instanceof Error ? error.message : "Failed to build PDF.",
    );
  }
};
