 export const currencies = [
        { value: "USD", label: "USD — US Dollar" },
        { value: "EUR", label: "EUR — Euro" },
        { value: "GBP", label: "GBP — British Pound" },
        { value: "BDT", label: "BDT — Bangladeshi Taka" },
        { value: "INR", label: "INR — Indian Rupee" },
        { value: "JPY", label: "JPY — Japanese Yen" },
        { value: "AUD", label: "AUD — Australian Dollar" },
        { value: "CAD", label: "CAD — Canadian Dollar" },
        { value: "CNY", label: "CNY — Chinese Yuan" },
        { value: "SGD", label: "SGD — Singapore Dollar" },
        { value: "AED", label: "AED — UAE Dirham" },
        { value: "SAR", label: "SAR — Saudi Riyal" },
        { value: "MYR", label: "MYR — Malaysian Ringgit" },
        { value: "THB", label: "THB — Thai Baht" },
        { value: "KRW", label: "KRW — South Korean Won" },
        { value: "CHF", label: "CHF — Swiss Franc" },
        { value: "NZD", label: "NZD — New Zealand Dollar" },
        { value: "ZAR", label: "ZAR — South African Rand" },
        { value: "SEK", label: "SEK — Swedish Krona" },
        { value: "NOK", label: "NOK — Norwegian Krone" },
        { value: "HKD", label: "HKD — Hong Kong Dollar" },
        { value: "PKR", label: "PKR — Pakistani Rupee" },
        { value: "LKR", label: "LKR — Sri Lankan Rupee" },
        { value: "IDR", label: "IDR — Indonesian Rupiah" },
        { value: "PHP", label: "PHP — Philippine Peso" },
        { value: "VND", label: "VND — Vietnamese Dong" },
        { value: "EGP", label: "EGP — Egyptian Pound" },
        { value: "TRY", label: "TRY — Turkish Lira" },
        { value: "BRL", label: "BRL — Brazilian Real" },
        { value: "MXN", label: "MXN — Mexican Peso" },
    ];